### YamlMime:ManagedReference
items:
- uid: Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.CommandConfigurationTest
  commentId: T:Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.CommandConfigurationTest
  id: CommandConfigurationTest
  parent: Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests
  children:
  - Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.CommandConfigurationTest.#ctor(Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.CommandConfigurationTest.CommandConfigurationTestFixture)
  - Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.CommandConfigurationTest.Constructed_select_query_CommandBuilder_throws_when_negative_CommandTimeout_is_used
  langs:
  - csharp
  - vb
  name: CommandConfigurationTest
  nameWithType: CommandConfigurationTest
  fullName: Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.CommandConfigurationTest
  type: Class
  source:
    remote:
      path: test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/CommandConfigurationTest.cs
      branch: dev
      repo: https://github.com/aspnet/EntityFramework.git
    id: CommandConfigurationTest
    path: test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/CommandConfigurationTest.cs
    startLine: 10
  assemblies:
  - Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests
  namespace: Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests
  syntax:
    content: 'public class CommandConfigurationTest : IClassFixture<CommandConfigurationTest.CommandConfigurationTestFixture>'
    content.vb: >-
      Public Class CommandConfigurationTest
          Inherits IClassFixture(Of CommandConfigurationTest.CommandConfigurationTestFixture)
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.CommandConfigurationTest.#ctor(Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.CommandConfigurationTest.CommandConfigurationTestFixture)
  commentId: M:Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.CommandConfigurationTest.#ctor(Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.CommandConfigurationTest.CommandConfigurationTestFixture)
  id: '#ctor(Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.CommandConfigurationTest.CommandConfigurationTestFixture)'
  parent: Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.CommandConfigurationTest
  langs:
  - csharp
  - vb
  name: CommandConfigurationTest(CommandConfigurationTest.CommandConfigurationTestFixture)
  nameWithType: CommandConfigurationTest.CommandConfigurationTest(CommandConfigurationTest.CommandConfigurationTestFixture)
  fullName: Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.CommandConfigurationTest.CommandConfigurationTest(Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.CommandConfigurationTest.CommandConfigurationTestFixture)
  type: Constructor
  source:
    remote:
      path: test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/CommandConfigurationTest.cs
      branch: dev
      repo: https://github.com/aspnet/EntityFramework.git
    id: .ctor
    path: test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/CommandConfigurationTest.cs
    startLine: 16
  assemblies:
  - Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests
  namespace: Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests
  syntax:
    content: public CommandConfigurationTest(CommandConfigurationTest.CommandConfigurationTestFixture fixture)
    content.vb: Public Sub New(fixture As CommandConfigurationTest.CommandConfigurationTestFixture)
    parameters:
    - id: fixture
      type: Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.CommandConfigurationTest.CommandConfigurationTestFixture
  overload: Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.CommandConfigurationTest.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.CommandConfigurationTest.Constructed_select_query_CommandBuilder_throws_when_negative_CommandTimeout_is_used
  commentId: M:Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.CommandConfigurationTest.Constructed_select_query_CommandBuilder_throws_when_negative_CommandTimeout_is_used
  id: Constructed_select_query_CommandBuilder_throws_when_negative_CommandTimeout_is_used
  parent: Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.CommandConfigurationTest
  langs:
  - csharp
  - vb
  name: Constructed_select_query_CommandBuilder_throws_when_negative_CommandTimeout_is_used()
  nameWithType: CommandConfigurationTest.Constructed_select_query_CommandBuilder_throws_when_negative_CommandTimeout_is_used()
  fullName: Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.CommandConfigurationTest.Constructed_select_query_CommandBuilder_throws_when_negative_CommandTimeout_is_used()
  type: Method
  source:
    remote:
      path: test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/CommandConfigurationTest.cs
      branch: dev
      repo: https://github.com/aspnet/EntityFramework.git
    id: Constructed_select_query_CommandBuilder_throws_when_negative_CommandTimeout_is_used
    path: test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/CommandConfigurationTest.cs
    startLine: 44
  assemblies:
  - Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests
  namespace: Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests
  syntax:
    content: public void Constructed_select_query_CommandBuilder_throws_when_negative_CommandTimeout_is_used()
    content.vb: Public Sub Constructed_select_query_CommandBuilder_throws_when_negative_CommandTimeout_is_used
  overload: Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.CommandConfigurationTest.Constructed_select_query_CommandBuilder_throws_when_negative_CommandTimeout_is_used*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests
  commentId: N:Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests
  isExternal: false
  name: Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests
  nameWithType: Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests
  fullName: Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.CommandConfigurationTest.#ctor*
  commentId: Overload:Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.CommandConfigurationTest.#ctor
  isExternal: false
  name: CommandConfigurationTest
  nameWithType: CommandConfigurationTest.CommandConfigurationTest
  fullName: Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.CommandConfigurationTest.CommandConfigurationTest
- uid: Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.CommandConfigurationTest.CommandConfigurationTestFixture
  commentId: T:Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.CommandConfigurationTest.CommandConfigurationTestFixture
  parent: Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests
  isExternal: false
  name: CommandConfigurationTest.CommandConfigurationTestFixture
  nameWithType: CommandConfigurationTest.CommandConfigurationTestFixture
  fullName: Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.CommandConfigurationTest.CommandConfigurationTestFixture
- uid: Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.CommandConfigurationTest.Constructed_select_query_CommandBuilder_throws_when_negative_CommandTimeout_is_used*
  commentId: Overload:Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.CommandConfigurationTest.Constructed_select_query_CommandBuilder_throws_when_negative_CommandTimeout_is_used
  isExternal: false
  name: Constructed_select_query_CommandBuilder_throws_when_negative_CommandTimeout_is_used
  nameWithType: CommandConfigurationTest.Constructed_select_query_CommandBuilder_throws_when_negative_CommandTimeout_is_used
  fullName: Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.CommandConfigurationTest.Constructed_select_query_CommandBuilder_throws_when_negative_CommandTimeout_is_used
