### YamlMime:ManagedReference
items:
- uid: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.Whiteboard
  commentId: T:Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.Whiteboard
  id: PropertyValuesTestBase`2.Whiteboard
  parent: Microsoft.EntityFrameworkCore.Specification.Tests
  children:
  - Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.Whiteboard.AssetTag
  - Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.Whiteboard.iD
  - Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.Whiteboard.Office
  langs:
  - csharp
  - vb
  name: PropertyValuesTestBase<TTestStore, TFixture>.Whiteboard
  nameWithType: PropertyValuesTestBase<TTestStore, TFixture>.Whiteboard
  fullName: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase<TTestStore, TFixture>.Whiteboard
  type: Class
  source:
    remote:
      path: src/Microsoft.EntityFrameworkCore.Specification.Tests/PropertyValuesTestBase.cs
      branch: dev
      repo: https://github.com/aspnet/EntityFramework.git
    id: Whiteboard
    path: src/Microsoft.EntityFrameworkCore.Specification.Tests/PropertyValuesTestBase.cs
    startLine: 1938
  assemblies:
  - Microsoft.EntityFrameworkCore.Specification.Tests
  namespace: Microsoft.EntityFrameworkCore.Specification.Tests
  syntax:
    content: protected class Whiteboard
    content.vb: Protected Class Whiteboard
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  nameWithType.vb: PropertyValuesTestBase(Of TTestStore, TFixture).Whiteboard
  modifiers.csharp:
  - protected
  - class
  modifiers.vb:
  - Protected
  - Class
  fullName.vb: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase(Of TTestStore, TFixture).Whiteboard
  name.vb: PropertyValuesTestBase(Of TTestStore, TFixture).Whiteboard
- uid: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.Whiteboard.iD
  commentId: P:Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.Whiteboard.iD
  id: iD
  parent: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.Whiteboard
  langs:
  - csharp
  - vb
  name: iD
  nameWithType: PropertyValuesTestBase<TTestStore, TFixture>.Whiteboard.iD
  fullName: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase<TTestStore, TFixture>.Whiteboard.iD
  type: Property
  source:
    remote:
      path: src/Microsoft.EntityFrameworkCore.Specification.Tests/PropertyValuesTestBase.cs
      branch: dev
      repo: https://github.com/aspnet/EntityFramework.git
    id: iD
    path: src/Microsoft.EntityFrameworkCore.Specification.Tests/PropertyValuesTestBase.cs
    startLine: 1940
  assemblies:
  - Microsoft.EntityFrameworkCore.Specification.Tests
  namespace: Microsoft.EntityFrameworkCore.Specification.Tests
  syntax:
    content: public byte[] iD { get; set; }
    content.vb: Public Property iD As Byte()
    parameters: []
    return:
      type: System.Byte[]
  nameWithType.vb: PropertyValuesTestBase(Of TTestStore, TFixture).Whiteboard.iD
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
  fullName.vb: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase(Of TTestStore, TFixture).Whiteboard.iD
- uid: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.Whiteboard.AssetTag
  commentId: P:Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.Whiteboard.AssetTag
  id: AssetTag
  parent: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.Whiteboard
  langs:
  - csharp
  - vb
  name: AssetTag
  nameWithType: PropertyValuesTestBase<TTestStore, TFixture>.Whiteboard.AssetTag
  fullName: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase<TTestStore, TFixture>.Whiteboard.AssetTag
  type: Property
  source:
    remote:
      path: src/Microsoft.EntityFrameworkCore.Specification.Tests/PropertyValuesTestBase.cs
      branch: dev
      repo: https://github.com/aspnet/EntityFramework.git
    id: AssetTag
    path: src/Microsoft.EntityFrameworkCore.Specification.Tests/PropertyValuesTestBase.cs
    startLine: 1941
  assemblies:
  - Microsoft.EntityFrameworkCore.Specification.Tests
  namespace: Microsoft.EntityFrameworkCore.Specification.Tests
  syntax:
    content: public string AssetTag { get; set; }
    content.vb: Public Property AssetTag As String
    parameters: []
    return:
      type: System.String
  nameWithType.vb: PropertyValuesTestBase(Of TTestStore, TFixture).Whiteboard.AssetTag
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
  fullName.vb: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase(Of TTestStore, TFixture).Whiteboard.AssetTag
- uid: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.Whiteboard.Office
  commentId: P:Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.Whiteboard.Office
  id: Office
  parent: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.Whiteboard
  langs:
  - csharp
  - vb
  name: Office
  nameWithType: PropertyValuesTestBase<TTestStore, TFixture>.Whiteboard.Office
  fullName: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase<TTestStore, TFixture>.Whiteboard.Office
  type: Property
  source:
    remote:
      path: src/Microsoft.EntityFrameworkCore.Specification.Tests/PropertyValuesTestBase.cs
      branch: dev
      repo: https://github.com/aspnet/EntityFramework.git
    id: Office
    path: src/Microsoft.EntityFrameworkCore.Specification.Tests/PropertyValuesTestBase.cs
    startLine: 1942
  assemblies:
  - Microsoft.EntityFrameworkCore.Specification.Tests
  namespace: Microsoft.EntityFrameworkCore.Specification.Tests
  syntax:
    content: public PropertyValuesTestBase<TTestStore, TFixture>.Office Office { get; set; }
    content.vb: Public Property Office As PropertyValuesTestBase(Of TTestStore, TFixture).Office
    parameters: []
    return:
      type: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.Office
  nameWithType.vb: PropertyValuesTestBase(Of TTestStore, TFixture).Whiteboard.Office
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
  fullName.vb: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase(Of TTestStore, TFixture).Whiteboard.Office
references:
- uid: Microsoft.EntityFrameworkCore.Specification.Tests
  commentId: N:Microsoft.EntityFrameworkCore.Specification.Tests
  isExternal: false
  name: Microsoft.EntityFrameworkCore.Specification.Tests
  nameWithType: Microsoft.EntityFrameworkCore.Specification.Tests
  fullName: Microsoft.EntityFrameworkCore.Specification.Tests
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: System.Byte[]
  name: Byte[]
  nameWithType: Byte[]
  fullName: System.Byte[]
  nameWithType.vb: Byte()
  fullname.vb: System.Byte()
  name.vb: Byte()
  spec.csharp:
  - uid: System.Byte
    name: Byte
    nameWithType: Byte
    fullName: System.Byte
    isExternal: true
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
  spec.vb:
  - uid: System.Byte
    name: Byte
    nameWithType: Byte
    fullName: System.Byte
    isExternal: true
  - name: ()
    nameWithType: ()
    fullName: ()
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.Office
  commentId: T:Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.Office
  parent: Microsoft.EntityFrameworkCore.Specification.Tests
  isExternal: false
  name: PropertyValuesTestBase.Office<>
  nameWithType: PropertyValuesTestBase.Office<>
  fullName: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase.Office<>
  nameWithType.vb: PropertyValuesTestBase.Office(Of )
  fullname.vb: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase.Office(Of )
  name.vb: PropertyValuesTestBase.Office(Of )
  spec.csharp:
  - uid: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.Office
    name: PropertyValuesTestBase.Office
    nameWithType: PropertyValuesTestBase.Office
    fullName: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase.Office
  - name: <
    nameWithType: <
    fullName: <
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.Office
    name: PropertyValuesTestBase.Office
    nameWithType: PropertyValuesTestBase.Office
    fullName: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase.Office
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: )
    nameWithType: )
    fullName: )
