### YamlMime:ManagedReference
items:
- uid: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.PastEmployee
  commentId: T:Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.PastEmployee
  id: PropertyValuesTestBase`2.PastEmployee
  parent: Microsoft.EntityFrameworkCore.Specification.Tests
  children:
  - Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.PastEmployee.TerminationDate
  langs:
  - csharp
  - vb
  name: PropertyValuesTestBase<TTestStore, TFixture>.PastEmployee
  nameWithType: PropertyValuesTestBase<TTestStore, TFixture>.PastEmployee
  fullName: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase<TTestStore, TFixture>.PastEmployee
  type: Class
  source:
    remote:
      path: src/Microsoft.EntityFrameworkCore.Specification.Tests/PropertyValuesTestBase.cs
      branch: dev
      repo: https://github.com/aspnet/EntityFramework.git
    id: PastEmployee
    path: src/Microsoft.EntityFrameworkCore.Specification.Tests/PropertyValuesTestBase.cs
    startLine: 1961
  assemblies:
  - Microsoft.EntityFrameworkCore.Specification.Tests
  namespace: Microsoft.EntityFrameworkCore.Specification.Tests
  syntax:
    content: 'protected class PastEmployee : PropertyValuesTestBase<TTestStore, TFixture>.Employee'
    content.vb: >-
      Protected Class PastEmployee
          Inherits PropertyValuesTestBase(Of TTestStore, TFixture).Employee
  inheritance:
  - System.Object
  - Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.UnMappedPersonBase
  - Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.Employee
  inheritedMembers:
  - Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.Employee.EmployeeId
  - Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.UnMappedPersonBase.FirstName
  - Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.UnMappedPersonBase.LastName
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  nameWithType.vb: PropertyValuesTestBase(Of TTestStore, TFixture).PastEmployee
  modifiers.csharp:
  - protected
  - class
  modifiers.vb:
  - Protected
  - Class
  fullName.vb: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase(Of TTestStore, TFixture).PastEmployee
  name.vb: PropertyValuesTestBase(Of TTestStore, TFixture).PastEmployee
- uid: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.PastEmployee.TerminationDate
  commentId: P:Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.PastEmployee.TerminationDate
  id: TerminationDate
  parent: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.PastEmployee
  langs:
  - csharp
  - vb
  name: TerminationDate
  nameWithType: PropertyValuesTestBase<TTestStore, TFixture>.PastEmployee.TerminationDate
  fullName: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase<TTestStore, TFixture>.PastEmployee.TerminationDate
  type: Property
  source:
    remote:
      path: src/Microsoft.EntityFrameworkCore.Specification.Tests/PropertyValuesTestBase.cs
      branch: dev
      repo: https://github.com/aspnet/EntityFramework.git
    id: TerminationDate
    path: src/Microsoft.EntityFrameworkCore.Specification.Tests/PropertyValuesTestBase.cs
    startLine: 1963
  assemblies:
  - Microsoft.EntityFrameworkCore.Specification.Tests
  namespace: Microsoft.EntityFrameworkCore.Specification.Tests
  syntax:
    content: public DateTime TerminationDate { get; set; }
    content.vb: Public Property TerminationDate As Date
    parameters: []
    return:
      type: System.DateTime
  overload: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.PastEmployee.TerminationDate*
  nameWithType.vb: PropertyValuesTestBase(Of TTestStore, TFixture).PastEmployee.TerminationDate
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
  fullName.vb: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase(Of TTestStore, TFixture).PastEmployee.TerminationDate
references:
- uid: Microsoft.EntityFrameworkCore.Specification.Tests
  commentId: N:Microsoft.EntityFrameworkCore.Specification.Tests
  isExternal: false
  name: Microsoft.EntityFrameworkCore.Specification.Tests
  nameWithType: Microsoft.EntityFrameworkCore.Specification.Tests
  fullName: Microsoft.EntityFrameworkCore.Specification.Tests
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.UnMappedPersonBase
  commentId: T:Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.UnMappedPersonBase
  parent: Microsoft.EntityFrameworkCore.Specification.Tests
  isExternal: false
  name: PropertyValuesTestBase.UnMappedPersonBase<>
  nameWithType: PropertyValuesTestBase.UnMappedPersonBase<>
  fullName: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase.UnMappedPersonBase<>
  nameWithType.vb: PropertyValuesTestBase.UnMappedPersonBase(Of )
  fullname.vb: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase.UnMappedPersonBase(Of )
  name.vb: PropertyValuesTestBase.UnMappedPersonBase(Of )
  spec.csharp:
  - uid: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.UnMappedPersonBase
    name: PropertyValuesTestBase.UnMappedPersonBase
    nameWithType: PropertyValuesTestBase.UnMappedPersonBase
    fullName: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase.UnMappedPersonBase
  - name: <
    nameWithType: <
    fullName: <
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.UnMappedPersonBase
    name: PropertyValuesTestBase.UnMappedPersonBase
    nameWithType: PropertyValuesTestBase.UnMappedPersonBase
    fullName: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase.UnMappedPersonBase
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.Employee
  commentId: T:Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.Employee
  parent: Microsoft.EntityFrameworkCore.Specification.Tests
  isExternal: false
  name: PropertyValuesTestBase.Employee<>
  nameWithType: PropertyValuesTestBase.Employee<>
  fullName: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase.Employee<>
  nameWithType.vb: PropertyValuesTestBase.Employee(Of )
  fullname.vb: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase.Employee(Of )
  name.vb: PropertyValuesTestBase.Employee(Of )
  spec.csharp:
  - uid: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.Employee
    name: PropertyValuesTestBase.Employee
    nameWithType: PropertyValuesTestBase.Employee
    fullName: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase.Employee
  - name: <
    nameWithType: <
    fullName: <
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.Employee
    name: PropertyValuesTestBase.Employee
    nameWithType: PropertyValuesTestBase.Employee
    fullName: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase.Employee
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.Employee.EmployeeId
  commentId: P:Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.Employee.EmployeeId
  parent: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.Employee
  isExternal: false
  name: EmployeeId
  nameWithType: PropertyValuesTestBase<TTestStore, TFixture>.Employee.EmployeeId
  fullName: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase<TTestStore, TFixture>.Employee.EmployeeId
  nameWithType.vb: PropertyValuesTestBase(Of TTestStore, TFixture).Employee.EmployeeId
  fullname.vb: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase(Of TTestStore, TFixture).Employee.EmployeeId
- uid: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.UnMappedPersonBase.FirstName
  commentId: P:Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.UnMappedPersonBase.FirstName
  parent: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.UnMappedPersonBase
  isExternal: false
  name: FirstName
  nameWithType: PropertyValuesTestBase<TTestStore, TFixture>.UnMappedPersonBase.FirstName
  fullName: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase<TTestStore, TFixture>.UnMappedPersonBase.FirstName
  nameWithType.vb: PropertyValuesTestBase(Of TTestStore, TFixture).UnMappedPersonBase.FirstName
  fullname.vb: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase(Of TTestStore, TFixture).UnMappedPersonBase.FirstName
- uid: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.UnMappedPersonBase.LastName
  commentId: P:Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.UnMappedPersonBase.LastName
  parent: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.UnMappedPersonBase
  isExternal: false
  name: LastName
  nameWithType: PropertyValuesTestBase<TTestStore, TFixture>.UnMappedPersonBase.LastName
  fullName: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase<TTestStore, TFixture>.UnMappedPersonBase.LastName
  nameWithType.vb: PropertyValuesTestBase(Of TTestStore, TFixture).UnMappedPersonBase.LastName
  fullname.vb: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase(Of TTestStore, TFixture).UnMappedPersonBase.LastName
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.PastEmployee.TerminationDate*
  commentId: Overload:Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.PastEmployee.TerminationDate
  isExternal: false
  name: TerminationDate
  nameWithType: PropertyValuesTestBase<TTestStore, TFixture>.PastEmployee.TerminationDate
  fullName: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase<TTestStore, TFixture>.PastEmployee.TerminationDate
  nameWithType.vb: PropertyValuesTestBase(Of TTestStore, TFixture).PastEmployee.TerminationDate
  fullname.vb: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase(Of TTestStore, TFixture).PastEmployee.TerminationDate
- uid: System.DateTime
  commentId: T:System.DateTime
  parent: System
  isExternal: true
  name: DateTime
  nameWithType: DateTime
  fullName: System.DateTime
