### YamlMime:ManagedReference
items:
- uid: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.IAttributeConfiguration
  commentId: T:Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.IAttributeConfiguration
  id: IAttributeConfiguration
  parent: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal
  children:
  - Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.IAttributeConfiguration.AttributeBody
  langs:
  - csharp
  - vb
  name: IAttributeConfiguration
  nameWithType: IAttributeConfiguration
  fullName: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.IAttributeConfiguration
  type: Interface
  source:
    remote:
      path: src/Microsoft.EntityFrameworkCore.Design/Scaffolding/Configuration/Internal/IAttributeConfiguration.cs
      branch: dev
      repo: https://github.com/aspnet/EntityFramework.git
    id: IAttributeConfiguration
    path: src/Microsoft.EntityFrameworkCore.Design/Scaffolding/Configuration/Internal/IAttributeConfiguration.cs
    startLine: 9
  assemblies:
  - Microsoft.EntityFrameworkCore.Design
  namespace: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal
  summary: "\n    This API supports the Entity Framework Core infrastructure and is not intended to be used\n    directly from your code. This API may change or be removed in future releases.\n"
  example: []
  syntax:
    content: public interface IAttributeConfiguration
    content.vb: Public Interface IAttributeConfiguration
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.IAttributeConfiguration.AttributeBody
  commentId: P:Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.IAttributeConfiguration.AttributeBody
  id: AttributeBody
  parent: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.IAttributeConfiguration
  langs:
  - csharp
  - vb
  name: AttributeBody
  nameWithType: IAttributeConfiguration.AttributeBody
  fullName: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.IAttributeConfiguration.AttributeBody
  type: Property
  source:
    remote:
      path: src/Microsoft.EntityFrameworkCore.Design/Scaffolding/Configuration/Internal/IAttributeConfiguration.cs
      branch: dev
      repo: https://github.com/aspnet/EntityFramework.git
    id: AttributeBody
    path: src/Microsoft.EntityFrameworkCore.Design/Scaffolding/Configuration/Internal/IAttributeConfiguration.cs
    startLine: 15
  assemblies:
  - Microsoft.EntityFrameworkCore.Design
  namespace: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal
  summary: "\n    This API supports the Entity Framework Core infrastructure and is not intended to be used\n    directly from your code. This API may change or be removed in future releases.\n"
  example: []
  syntax:
    content: string AttributeBody { get; }
    content.vb: ReadOnly Property AttributeBody As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
references:
- uid: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal
  commentId: N:Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal
  isExternal: false
  name: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal
  nameWithType: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal
  fullName: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
