### YamlMime:ManagedReference
items:
- uid: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.MailRoom
  commentId: T:Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.MailRoom
  id: PropertyValuesTestBase`2.MailRoom
  parent: Microsoft.EntityFrameworkCore.Specification.Tests
  children:
  - Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.MailRoom.Building
  - Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.MailRoom.BuildingId
  - Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.MailRoom.id
  langs:
  - csharp
  - vb
  name: PropertyValuesTestBase<TTestStore, TFixture>.MailRoom
  nameWithType: PropertyValuesTestBase<TTestStore, TFixture>.MailRoom
  fullName: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase<TTestStore, TFixture>.MailRoom
  type: Class
  source:
    remote:
      path: src/Microsoft.EntityFrameworkCore.Specification.Tests/PropertyValuesTestBase.cs
      branch: dev
      repo: https://github.com/aspnet/EntityFramework.git
    id: MailRoom
    path: src/Microsoft.EntityFrameworkCore.Specification.Tests/PropertyValuesTestBase.cs
    startLine: 1902
  assemblies:
  - Microsoft.EntityFrameworkCore.Specification.Tests
  namespace: Microsoft.EntityFrameworkCore.Specification.Tests
  syntax:
    content: protected class MailRoom
    content.vb: Protected Class MailRoom
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  nameWithType.vb: PropertyValuesTestBase(Of TTestStore, TFixture).MailRoom
  modifiers.csharp:
  - protected
  - class
  modifiers.vb:
  - Protected
  - Class
  fullName.vb: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase(Of TTestStore, TFixture).MailRoom
  name.vb: PropertyValuesTestBase(Of TTestStore, TFixture).MailRoom
- uid: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.MailRoom.id
  commentId: P:Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.MailRoom.id
  id: id
  parent: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.MailRoom
  langs:
  - csharp
  - vb
  name: id
  nameWithType: PropertyValuesTestBase<TTestStore, TFixture>.MailRoom.id
  fullName: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase<TTestStore, TFixture>.MailRoom.id
  type: Property
  source:
    remote:
      path: src/Microsoft.EntityFrameworkCore.Specification.Tests/PropertyValuesTestBase.cs
      branch: dev
      repo: https://github.com/aspnet/EntityFramework.git
    id: id
    path: src/Microsoft.EntityFrameworkCore.Specification.Tests/PropertyValuesTestBase.cs
    startLine: 1904
  assemblies:
  - Microsoft.EntityFrameworkCore.Specification.Tests
  namespace: Microsoft.EntityFrameworkCore.Specification.Tests
  syntax:
    content: public int id { get; set; }
    content.vb: Public Property id As Integer
    parameters: []
    return:
      type: System.Int32
  overload: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.MailRoom.id*
  nameWithType.vb: PropertyValuesTestBase(Of TTestStore, TFixture).MailRoom.id
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
  fullName.vb: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase(Of TTestStore, TFixture).MailRoom.id
- uid: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.MailRoom.Building
  commentId: P:Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.MailRoom.Building
  id: Building
  parent: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.MailRoom
  langs:
  - csharp
  - vb
  name: Building
  nameWithType: PropertyValuesTestBase<TTestStore, TFixture>.MailRoom.Building
  fullName: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase<TTestStore, TFixture>.MailRoom.Building
  type: Property
  source:
    remote:
      path: src/Microsoft.EntityFrameworkCore.Specification.Tests/PropertyValuesTestBase.cs
      branch: dev
      repo: https://github.com/aspnet/EntityFramework.git
    id: Building
    path: src/Microsoft.EntityFrameworkCore.Specification.Tests/PropertyValuesTestBase.cs
    startLine: 1905
  assemblies:
  - Microsoft.EntityFrameworkCore.Specification.Tests
  namespace: Microsoft.EntityFrameworkCore.Specification.Tests
  syntax:
    content: public PropertyValuesTestBase<TTestStore, TFixture>.Building Building { get; set; }
    content.vb: Public Property Building As PropertyValuesTestBase(Of TTestStore, TFixture).Building
    parameters: []
    return:
      type: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.Building
  overload: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.MailRoom.Building*
  nameWithType.vb: PropertyValuesTestBase(Of TTestStore, TFixture).MailRoom.Building
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
  fullName.vb: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase(Of TTestStore, TFixture).MailRoom.Building
- uid: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.MailRoom.BuildingId
  commentId: P:Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.MailRoom.BuildingId
  id: BuildingId
  parent: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.MailRoom
  langs:
  - csharp
  - vb
  name: BuildingId
  nameWithType: PropertyValuesTestBase<TTestStore, TFixture>.MailRoom.BuildingId
  fullName: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase<TTestStore, TFixture>.MailRoom.BuildingId
  type: Property
  source:
    remote:
      path: src/Microsoft.EntityFrameworkCore.Specification.Tests/PropertyValuesTestBase.cs
      branch: dev
      repo: https://github.com/aspnet/EntityFramework.git
    id: BuildingId
    path: src/Microsoft.EntityFrameworkCore.Specification.Tests/PropertyValuesTestBase.cs
    startLine: 1906
  assemblies:
  - Microsoft.EntityFrameworkCore.Specification.Tests
  namespace: Microsoft.EntityFrameworkCore.Specification.Tests
  syntax:
    content: public Guid BuildingId { get; set; }
    content.vb: Public Property BuildingId As Guid
    parameters: []
    return:
      type: System.Guid
  overload: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.MailRoom.BuildingId*
  nameWithType.vb: PropertyValuesTestBase(Of TTestStore, TFixture).MailRoom.BuildingId
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
  fullName.vb: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase(Of TTestStore, TFixture).MailRoom.BuildingId
references:
- uid: Microsoft.EntityFrameworkCore.Specification.Tests
  commentId: N:Microsoft.EntityFrameworkCore.Specification.Tests
  isExternal: false
  name: Microsoft.EntityFrameworkCore.Specification.Tests
  nameWithType: Microsoft.EntityFrameworkCore.Specification.Tests
  fullName: Microsoft.EntityFrameworkCore.Specification.Tests
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.MailRoom.id*
  commentId: Overload:Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.MailRoom.id
  isExternal: false
  name: id
  nameWithType: PropertyValuesTestBase<TTestStore, TFixture>.MailRoom.id
  fullName: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase<TTestStore, TFixture>.MailRoom.id
  nameWithType.vb: PropertyValuesTestBase(Of TTestStore, TFixture).MailRoom.id
  fullname.vb: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase(Of TTestStore, TFixture).MailRoom.id
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.MailRoom.Building*
  commentId: Overload:Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.MailRoom.Building
  isExternal: false
  name: Building
  nameWithType: PropertyValuesTestBase<TTestStore, TFixture>.MailRoom.Building
  fullName: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase<TTestStore, TFixture>.MailRoom.Building
  nameWithType.vb: PropertyValuesTestBase(Of TTestStore, TFixture).MailRoom.Building
  fullname.vb: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase(Of TTestStore, TFixture).MailRoom.Building
- uid: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.Building
  commentId: T:Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.Building
  parent: Microsoft.EntityFrameworkCore.Specification.Tests
  isExternal: false
  name: PropertyValuesTestBase.Building<>
  nameWithType: PropertyValuesTestBase.Building<>
  fullName: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase.Building<>
  nameWithType.vb: PropertyValuesTestBase.Building(Of )
  fullname.vb: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase.Building(Of )
  name.vb: PropertyValuesTestBase.Building(Of )
  spec.csharp:
  - uid: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.Building
    name: PropertyValuesTestBase.Building
    nameWithType: PropertyValuesTestBase.Building
    fullName: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase.Building
  - name: <
    nameWithType: <
    fullName: <
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.Building
    name: PropertyValuesTestBase.Building
    nameWithType: PropertyValuesTestBase.Building
    fullName: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase.Building
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.MailRoom.BuildingId*
  commentId: Overload:Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase`2.MailRoom.BuildingId
  isExternal: false
  name: BuildingId
  nameWithType: PropertyValuesTestBase<TTestStore, TFixture>.MailRoom.BuildingId
  fullName: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase<TTestStore, TFixture>.MailRoom.BuildingId
  nameWithType.vb: PropertyValuesTestBase(Of TTestStore, TFixture).MailRoom.BuildingId
  fullname.vb: Microsoft.EntityFrameworkCore.Specification.Tests.PropertyValuesTestBase(Of TTestStore, TFixture).MailRoom.BuildingId
- uid: System.Guid
  commentId: T:System.Guid
  parent: System
  isExternal: true
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
