### YamlMime:ManagedReference
items:
- uid: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal
  commentId: N:Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal
  id: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal
  children:
  - Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.AttributeConfiguration
  - Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.CustomConfiguration
  - Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.EntityConfiguration
  - Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.FluentApiConfiguration
  - Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.IAttributeConfiguration
  - Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.IFluentApiConfiguration
  - Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.IndexConfiguration
  - Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.KeyFluentApiConfiguration
  - Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.ModelConfiguration
  - Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.NavigationPropertyConfiguration
  - Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.NavigationPropertyInitializerConfiguration
  - Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.OptionsBuilderConfiguration
  - Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.PropertyConfiguration
  - Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.RelationshipConfiguration
  - Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.SequenceConfiguration
  langs:
  - csharp
  - vb
  name: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal
  nameWithType: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal
  fullName: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal
  type: Namespace
  assemblies:
  - Microsoft.EntityFrameworkCore.Design
references:
- uid: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.AttributeConfiguration
  commentId: T:Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.AttributeConfiguration
  parent: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal
  isExternal: false
  name: AttributeConfiguration
  nameWithType: AttributeConfiguration
  fullName: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.AttributeConfiguration
- uid: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.CustomConfiguration
  commentId: T:Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.CustomConfiguration
  parent: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal
  isExternal: false
  name: CustomConfiguration
  nameWithType: CustomConfiguration
  fullName: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.CustomConfiguration
- uid: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.EntityConfiguration
  commentId: T:Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.EntityConfiguration
  parent: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal
  isExternal: false
  name: EntityConfiguration
  nameWithType: EntityConfiguration
  fullName: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.EntityConfiguration
- uid: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.FluentApiConfiguration
  commentId: T:Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.FluentApiConfiguration
  parent: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal
  isExternal: false
  name: FluentApiConfiguration
  nameWithType: FluentApiConfiguration
  fullName: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.FluentApiConfiguration
- uid: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.IAttributeConfiguration
  commentId: T:Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.IAttributeConfiguration
  parent: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal
  isExternal: false
  name: IAttributeConfiguration
  nameWithType: IAttributeConfiguration
  fullName: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.IAttributeConfiguration
- uid: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.IFluentApiConfiguration
  commentId: T:Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.IFluentApiConfiguration
  parent: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal
  isExternal: false
  name: IFluentApiConfiguration
  nameWithType: IFluentApiConfiguration
  fullName: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.IFluentApiConfiguration
- uid: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.IndexConfiguration
  commentId: T:Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.IndexConfiguration
  parent: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal
  isExternal: false
  name: IndexConfiguration
  nameWithType: IndexConfiguration
  fullName: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.IndexConfiguration
- uid: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.KeyFluentApiConfiguration
  commentId: T:Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.KeyFluentApiConfiguration
  parent: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal
  isExternal: false
  name: KeyFluentApiConfiguration
  nameWithType: KeyFluentApiConfiguration
  fullName: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.KeyFluentApiConfiguration
- uid: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.ModelConfiguration
  commentId: T:Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.ModelConfiguration
  parent: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal
  isExternal: false
  name: ModelConfiguration
  nameWithType: ModelConfiguration
  fullName: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.ModelConfiguration
- uid: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.NavigationPropertyConfiguration
  commentId: T:Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.NavigationPropertyConfiguration
  parent: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal
  isExternal: false
  name: NavigationPropertyConfiguration
  nameWithType: NavigationPropertyConfiguration
  fullName: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.NavigationPropertyConfiguration
- uid: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.NavigationPropertyInitializerConfiguration
  commentId: T:Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.NavigationPropertyInitializerConfiguration
  parent: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal
  isExternal: false
  name: NavigationPropertyInitializerConfiguration
  nameWithType: NavigationPropertyInitializerConfiguration
  fullName: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.NavigationPropertyInitializerConfiguration
- uid: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.OptionsBuilderConfiguration
  commentId: T:Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.OptionsBuilderConfiguration
  parent: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal
  isExternal: false
  name: OptionsBuilderConfiguration
  nameWithType: OptionsBuilderConfiguration
  fullName: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.OptionsBuilderConfiguration
- uid: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.PropertyConfiguration
  commentId: T:Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.PropertyConfiguration
  parent: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal
  isExternal: false
  name: PropertyConfiguration
  nameWithType: PropertyConfiguration
  fullName: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.PropertyConfiguration
- uid: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.RelationshipConfiguration
  commentId: T:Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.RelationshipConfiguration
  parent: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal
  isExternal: false
  name: RelationshipConfiguration
  nameWithType: RelationshipConfiguration
  fullName: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.RelationshipConfiguration
- uid: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.SequenceConfiguration
  commentId: T:Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.SequenceConfiguration
  parent: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal
  isExternal: false
  name: SequenceConfiguration
  nameWithType: SequenceConfiguration
  fullName: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal.SequenceConfiguration
- uid: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal
  commentId: N:Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal
  isExternal: false
  name: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal
  nameWithType: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal
  fullName: Microsoft.EntityFrameworkCore.Scaffolding.Configuration.Internal
