### YamlMime:ManagedReference
items:
- uid: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest
  commentId: T:Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest
  id: DefaultValuesTest
  parent: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests
  children:
  - Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest.#ctor
  - Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest.Can_use_SQL_Server_default_values
  - Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest.Dispose
  - Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest.TestStore
  langs:
  - csharp
  - vb
  name: DefaultValuesTest
  nameWithType: DefaultValuesTest
  fullName: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest
  type: Class
  source:
    remote:
      path: test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/DefaultValuesTest.cs
      branch: dev
      repo: https://github.com/aspnet/EntityFramework.git
    id: DefaultValuesTest
    path: test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/DefaultValuesTest.cs
    startLine: 11
  assemblies:
  - Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests
  namespace: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests
  syntax:
    content: 'public class DefaultValuesTest : IDisposable'
    content.vb: >-
      Public Class DefaultValuesTest
          Implements IDisposable
  inheritance:
  - System.Object
  implements:
  - System.IDisposable
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest.Can_use_SQL_Server_default_values
  commentId: M:Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest.Can_use_SQL_Server_default_values
  id: Can_use_SQL_Server_default_values
  parent: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest
  langs:
  - csharp
  - vb
  name: Can_use_SQL_Server_default_values()
  nameWithType: DefaultValuesTest.Can_use_SQL_Server_default_values()
  fullName: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest.Can_use_SQL_Server_default_values()
  type: Method
  source:
    remote:
      path: test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/DefaultValuesTest.cs
      branch: dev
      repo: https://github.com/aspnet/EntityFramework.git
    id: Can_use_SQL_Server_default_values
    path: test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/DefaultValuesTest.cs
    startLine: 17
  assemblies:
  - Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests
  namespace: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests
  syntax:
    content: public void Can_use_SQL_Server_default_values()
    content.vb: Public Sub Can_use_SQL_Server_default_values
  overload: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest.Can_use_SQL_Server_default_values*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest.#ctor
  commentId: M:Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest.#ctor
  id: '#ctor'
  parent: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest
  langs:
  - csharp
  - vb
  name: DefaultValuesTest()
  nameWithType: DefaultValuesTest.DefaultValuesTest()
  fullName: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest.DefaultValuesTest()
  type: Constructor
  source:
    remote:
      path: test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/DefaultValuesTest.cs
      branch: dev
      repo: https://github.com/aspnet/EntityFramework.git
    id: .ctor
    path: test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/DefaultValuesTest.cs
    startLine: 72
  assemblies:
  - Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests
  namespace: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests
  syntax:
    content: public DefaultValuesTest()
    content.vb: Public Sub New
  overload: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest.TestStore
  commentId: P:Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest.TestStore
  id: TestStore
  parent: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest
  langs:
  - csharp
  - vb
  name: TestStore
  nameWithType: DefaultValuesTest.TestStore
  fullName: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest.TestStore
  type: Property
  source:
    remote:
      path: test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/DefaultValuesTest.cs
      branch: dev
      repo: https://github.com/aspnet/EntityFramework.git
    id: TestStore
    path: test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/DefaultValuesTest.cs
    startLine: 77
  assemblies:
  - Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests
  namespace: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests
  syntax:
    content: protected SqlServerTestStore TestStore { get; }
    content.vb: Protected ReadOnly Property TestStore As SqlServerTestStore
    parameters: []
    return:
      type: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.Utilities.SqlServerTestStore
  overload: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest.TestStore*
  modifiers.csharp:
  - protected
  - get
  modifiers.vb:
  - Protected
  - ReadOnly
- uid: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest.Dispose
  commentId: M:Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest.Dispose
  id: Dispose
  parent: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest
  langs:
  - csharp
  - vb
  name: Dispose()
  nameWithType: DefaultValuesTest.Dispose()
  fullName: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest.Dispose()
  type: Method
  source:
    remote:
      path: test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/DefaultValuesTest.cs
      branch: dev
      repo: https://github.com/aspnet/EntityFramework.git
    id: Dispose
    path: test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/DefaultValuesTest.cs
    startLine: 79
  assemblies:
  - Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests
  namespace: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests
  syntax:
    content: public virtual void Dispose()
    content.vb: Public Overridable Sub Dispose
  overload: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest.Dispose*
  implements:
  - System.IDisposable.Dispose
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
references:
- uid: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests
  commentId: N:Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests
  isExternal: false
  name: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests
  nameWithType: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests
  fullName: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.IDisposable
  commentId: T:System.IDisposable
  parent: System
  isExternal: true
  name: IDisposable
  nameWithType: IDisposable
  fullName: System.IDisposable
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest.Can_use_SQL_Server_default_values*
  commentId: Overload:Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest.Can_use_SQL_Server_default_values
  isExternal: false
  name: Can_use_SQL_Server_default_values
  nameWithType: DefaultValuesTest.Can_use_SQL_Server_default_values
  fullName: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest.Can_use_SQL_Server_default_values
- uid: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest.#ctor*
  commentId: Overload:Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest.#ctor
  isExternal: false
  name: DefaultValuesTest
  nameWithType: DefaultValuesTest.DefaultValuesTest
  fullName: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest.DefaultValuesTest
- uid: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest.TestStore*
  commentId: Overload:Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest.TestStore
  isExternal: false
  name: TestStore
  nameWithType: DefaultValuesTest.TestStore
  fullName: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest.TestStore
- uid: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.Utilities.SqlServerTestStore
  commentId: T:Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.Utilities.SqlServerTestStore
  parent: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.Utilities
  isExternal: false
  name: SqlServerTestStore
  nameWithType: SqlServerTestStore
  fullName: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.Utilities.SqlServerTestStore
- uid: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.Utilities
  commentId: N:Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.Utilities
  isExternal: false
  name: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.Utilities
  nameWithType: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.Utilities
  fullName: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.Utilities
- uid: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest.Dispose*
  commentId: Overload:Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest.Dispose
  isExternal: false
  name: Dispose
  nameWithType: DefaultValuesTest.Dispose
  fullName: Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.DefaultValuesTest.Dispose
- uid: System.IDisposable.Dispose
  commentId: M:System.IDisposable.Dispose
  parent: System.IDisposable
  isExternal: true
  name: Dispose()
  nameWithType: IDisposable.Dispose()
  fullName: System.IDisposable.Dispose()
  spec.csharp:
  - uid: System.IDisposable.Dispose
    name: Dispose
    nameWithType: IDisposable.Dispose
    fullName: System.IDisposable.Dispose
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.IDisposable.Dispose
    name: Dispose
    nameWithType: IDisposable.Dispose
    fullName: System.IDisposable.Dispose
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
